export interface Theme {
    isDark: boolean;
    bg: string;
    bgGrad: string;
    surface: string;
    surfaceAlt: string;
    border: string;
    borderHover: string;
    text: string;
    textSoft: string;
    textSec: string;
    textMut: string;
    accent: string;
    accentDk: string;
    accentBg: string;
    accentBd: string;
    success: string;
    successBg: string;
    danger: string;
    dangerBg: string;
    dangerTxt: string;
    warning: string;
    warningBg: string;
    warningTxt: string;
    info: string;
    infoBg: string;
    nominee: string;
    inputBg: string;
    inputBd: string;
    inputFocus: string;
    inputTxt: string;
    optBg: string;
    optTxt: string;
    headerBg: string;
    scroll: string;
    shadow: string;
    cardShadow: string;
    chartAxis: string;
    chartLabel: string;
    tipBg: string;
    tipBd: string;
    tipTxt: string;
    calFilter: string;
    ghostBg: string;
    ghostBd: string;
    ghostTxt: string;
    outlineTxt: string;
    outlineBd: string;
    cursor: string;
    barLabel: string;
    tagBg: (color: string) => string;
    gradStart: string;
    gradEnd: string;
    expBg: (color: string) => string;
}
export type ThemeName = 'dark' | 'light';
export declare const THEMES: Record<ThemeName, Theme>;
//# sourceMappingURL=themes.d.ts.map